### PR TITLE
Update to support swift pacakge manager

### PR DESCRIPTION
**Pull request by grangej**
- add Package.swift
- Resolve compile issue in Extensions.swift

### CODE REVIEW

**Comment by mkko** [comment]
Hi, and thank you for the contribution! Sorry for taking so long to get this through, I'll try to check this during the weekend.

**Review by mkko — APPROVED** [review]

**Comment by mkko** [comment]
Thanks for the contribution! And again, apologies for taking this long to get back to you.

**Comment by grangej** [comment]
@mkko awesome :D no problem, I understand busy life / work ;-)

**Comment by grangej** [comment]
@mkko for the package to be working you will need to release a new version on git.

**Comment by mkko** [comment]
I bumped the version, please let me know if there's any issues. Thanks!

**Comment by grangej** [comment]
Thank you again, sorry took son long to read this 😅

**Pull request merged**
